require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/SignalException:
  Exclude:
    - 'app/concepts/**/*'

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Lint/UnreachableCode:
  Exclude:
    - 'app/concepts/**/*'

Rails/FilePath:
  EnforcedStyle: arguments
