version: '3.9'

volumes:
  gem_cache:
  db_data:
  redis_data:

services:
  database:
    image: postgres:12.11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.14

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    ports:
      - '3000:3000'
    environment:
      RAILS_ENV: development
      DB_HOST: database
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: database
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - database
      - redis
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems