name: Main

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linters:
    runs-on: ubuntu-20.04

    steps:
      - name: Git clone our repo
        uses: actions/checkout@v3

      - name: Setup ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Run rubocop
        run: bundle exec rubocop

      - name: Run brakeman
        run: bundle exec brakeman

  tests:
    runs-on: ubuntu-20.04
    services:
      db:
        image: postgres:10.20-alpine
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pet_todo_api_test
          POSTGRES_HOST: localhost
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    env:
        DB_HOST: localhost
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
        RAILS_ENV: test

    steps:
      - name: Git clone our repo
        uses: actions/checkout@v3

      - name: Setup ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Setup db
        run: bin/rails db:setup

      - name: Run rspec
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_TEST_KEY }}
        run: bundle exec rspec
